
-- AKOLIAS SOCIAL ULTIMATE SCHEMA
-- Run after your existing setup. Safe/idempotent additions.

alter table public.profiles add column if not exists website text default '';
alter table public.profiles add column if not exists gender text;
alter table public.profiles add column if not exists date_of_birth date;
alter table public.profiles add column if not exists location text default '';
alter table public.profiles add column if not exists is_private boolean not null default false;
alter table public.profiles add column if not exists is_verified boolean not null default false;
alter table public.profiles add column if not exists profile_type text not null default 'personal';
alter table public.profiles add column if not exists category text default '';

alter table public.posts add column if not exists location text default '';
alter table public.posts add column if not exists comments_enabled boolean not null default true;
alter table public.posts add column if not exists hide_like_count boolean not null default false;
alter table public.posts add column if not exists archived boolean not null default false;
alter table public.posts add column if not exists scheduled_at timestamptz;
alter table public.posts add column if not exists is_sensitive boolean not null default false;

create table if not exists public.follow_requests(
 id uuid primary key default gen_random_uuid(),
 requester_id uuid not null references auth.users(id) on delete cascade,
 target_id uuid not null references auth.users(id) on delete cascade,
 status text not null default 'pending',
 created_at timestamptz not null default now(),
 unique(requester_id,target_id)
);

create table if not exists public.support_tickets(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 subject text not null default 'Support Request',
 message text not null,
 status text not null default 'open',
 priority text not null default 'normal',
 assigned_to uuid references auth.users(id) on delete set null,
 admin_reply text default '',
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table if not exists public.user_preferences(
 user_id uuid primary key references auth.users(id) on delete cascade,
 language text not null default 'en',
 activity_status boolean not null default true,
 read_receipts boolean not null default true,
 who_can_message text not null default 'everyone',
 who_can_comment text not null default 'everyone',
 who_can_tag text not null default 'everyone',
 who_can_mention text not null default 'everyone',
 sensitive_content text not null default 'standard',
 updated_at timestamptz not null default now()
);

create table if not exists public.muted_accounts(
 user_id uuid not null references auth.users(id) on delete cascade,
 muted_user_id uuid not null references auth.users(id) on delete cascade,
 mute_posts boolean not null default true,
 mute_stories boolean not null default true,
 mute_messages boolean not null default false,
 created_at timestamptz not null default now(),
 primary key(user_id,muted_user_id)
);

create table if not exists public.collections(
 id uuid primary key default gen_random_uuid(),
 user_id uuid not null references auth.users(id) on delete cascade,
 name text not null,
 created_at timestamptz not null default now()
);
create table if not exists public.collection_items(
 collection_id uuid not null references public.collections(id) on delete cascade,
 post_id uuid not null references public.posts(id) on delete cascade,
 created_at timestamptz not null default now(),
 primary key(collection_id,post_id)
);

create table if not exists public.comment_likes(
 comment_id uuid not null references public.comments(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 created_at timestamptz not null default now(),
 primary key(comment_id,user_id)
);

create table if not exists public.comment_replies(
 id uuid primary key default gen_random_uuid(),
 comment_id uuid not null references public.comments(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 body text not null,
 created_at timestamptz not null default now()
);

create table if not exists public.login_activity(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 user_agent text,
 ip_hash text,
 created_at timestamptz not null default now()
);

create table if not exists public.creator_analytics(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 metric_date date not null default current_date,
 profile_visits integer not null default 0,
 reach integer not null default 0,
 impressions integer not null default 0,
 link_clicks integer not null default 0,
 unique(user_id,metric_date)
);

create table if not exists public.admin_roles(
 user_id uuid primary key references auth.users(id) on delete cascade,
 role text not null default 'admin',
 created_at timestamptz not null default now()
);

create table if not exists public.admin_audit_log(
 id bigint generated by default as identity primary key,
 admin_id uuid references auth.users(id) on delete set null,
 target_user_id uuid references auth.users(id) on delete set null,
 action text not null,
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);

-- RLS
alter table public.support_tickets enable row level security;
drop policy if exists "ticket own read" on public.support_tickets;
create policy "ticket own read" on public.support_tickets for select to authenticated using(auth.uid()=user_id or public.is_admin());
drop policy if exists "ticket own insert" on public.support_tickets;
create policy "ticket own insert" on public.support_tickets for insert to authenticated with check(auth.uid()=user_id);
drop policy if exists "ticket admin update" on public.support_tickets;
create policy "ticket admin update" on public.support_tickets for update to authenticated using(public.is_admin());

alter table public.user_preferences enable row level security;
drop policy if exists "prefs own" on public.user_preferences;
create policy "prefs own" on public.user_preferences for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);

alter table public.follow_requests enable row level security;
drop policy if exists "follow requests own" on public.follow_requests;
create policy "follow requests own" on public.follow_requests for select to authenticated using(auth.uid()=requester_id or auth.uid()=target_id);
drop policy if exists "follow requests insert" on public.follow_requests;
create policy "follow requests insert" on public.follow_requests for insert to authenticated with check(auth.uid()=requester_id);
drop policy if exists "follow requests update target" on public.follow_requests;
create policy "follow requests update target" on public.follow_requests for update to authenticated using(auth.uid()=target_id);

alter table public.muted_accounts enable row level security;
drop policy if exists "mute own" on public.muted_accounts;
create policy "mute own" on public.muted_accounts for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);

alter table public.collections enable row level security;
drop policy if exists "collections own" on public.collections;
create policy "collections own" on public.collections for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);

alter table public.collection_items enable row level security;
drop policy if exists "collection items own" on public.collection_items;
create policy "collection items own" on public.collection_items for all to authenticated using(exists(select 1 from public.collections c where c.id=collection_id and c.user_id=auth.uid())) with check(exists(select 1 from public.collections c where c.id=collection_id and c.user_id=auth.uid()));

-- Helpful indexes
create index if not exists support_tickets_user_idx on public.support_tickets(user_id,created_at desc);
create index if not exists follow_requests_target_idx on public.follow_requests(target_id,status,created_at desc);
create index if not exists creator_analytics_user_idx on public.creator_analytics(user_id,metric_date desc);
